### ISSUE TITLE
Service failing with ExecStart=/home/user/.local/bin/pp-to-amd-epp (code=exited, status=203/EXEC)

### ISSUE THREAD

**Issue by anzigo** [marcinx64/pp-to-amd-epp#1]
The service fails to start after running the install script. I had to edit the ExecStart line in the pp-to-amd-epp.service file to explicitly use python like this:

ExecStart=python3 /home/user/.local/bin/pp-to-amd-epp

I'm on Fedora 39, and the service is working as it should on an Asus ROG G14 GA402RK.

**Comment by marcinx64** [comment]
Should be fixed in: [https://github.com/marcinx64/pp-to-amd-epp/commit/a9d2cecf32a3dc77aa0fbe1c81ad71080805e43f](a9d2cec)

**Comment by marcinx64** [comment]
Fixed in: [a9d2cec](https://github.com/marcinx64/pp-to-amd-epp/commit/a9d2cecf32a3dc77aa0fbe1c81ad71080805e43f)
